# Generated by Django 4.1.5 on 2023-02-17 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='tg_chat_id',
            new_name='chat_id',
        ),
    ]
